### ISSUE TITLE
김태현의 코드 리뷰입니다!

### ISSUE THREAD

**Issue by ted0729** [ddoddiworld/makeui#2]
⭐️⭐️⭐️ 전체적으로 가독성이 좋아서 금방 이해할 수 있었습니다 ! ⭐️⭐️⭐️

- Button🐣
: size별로 porps 하신 점이 인상깊었습니다.  저는 왜 생각도 못했을까요??

- Input 🐣
: 저장(추가하기)버튼에 !name || !price 로 조건을 주신걸 보고 저의 name.length === 0 && price.length === 0 조건과 비교 하게 되었는데, 제 조건엔 오류가 있다는걸 알게되었네요. name이나 price중 하나만 입력해도 조건이 충족되니까요.. 좋은 참조가 됬습니다.
: 가격의 onChange식이 따로 함수로 빠져나왔으면 좀 더 가독하기 좋았을거같다는 개인적인 생각입니다..! 

- modal🐣
: 개인적으로 if문을 좋아해서 return 문에 if로 조건이 들어가서 편안하게 감상했습니다 ㅎㅎ

항상 큰 도움 주시는 소영님 감사합니다. 더 도와주세용 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

**Comment by ddoddiworld** [comment]
🙋🏻‍♀️ 태현A(ce)님 안녕하세요!!

우선 칭찬 위주의 코드 리뷰 주셔서 너무 감사합니다. 😭

안그래도 요즘 구현이 마음대로 잘 안되고 있어서 심적으로 좌절의 늪에서 허우적대고 있었는데,
태현님의 리뷰 덕분에 타인에게도 도움이 되고 있다고 느껴서 다시 마음이 몽글몽글 해 졌어요! 😄

피드백 주신 onChange는 간단한 함수라 inline 형태로 넣어야겠다~ 했는데
확실히 추후 기능이 추가되거나 수정할때 불편할 수도 있겠다..! 라는 생각이 드네요. 🤔
앞으로는 함수로 분리해서 관리하도록 해 보겠습니다!

소중한 피드백에 다시한번 감사드리며 남은 과제도 파이팅입니다!!
