### ISSUE TITLE
Lv3 페어리뷰

### ISSUE THREAD

**Issue by Banana-Master** [ddoddiworld/makeui#3]
### Button
- color뿐만 아니라 size까지 props로 입력받아서 중복을 최소화 시킨 부분이 인상깊었습니다.

### Input
- `if (!name || !price)` 입력이 안된 부분을 찾는 if문 조건을 `!`를 이용하여 구현하신 점이 인상깊었습니다.

### Modal
- 2개의 모달창을 각각의 useState로 구현한 것이 아닌 type 을 지정해서 하나로 구현하신 점을 보고 많이 배웠습니다.

### Select
- 마찬가지로 각각의 select에 useState를 지정한 것이 아닌 type을 지정해서 하나로 구현 하신 점이 좋았습니다.
- map함수에 key값을 추가하여 console창에 Warning이 뜨지 않게 하면 좋을 것 같습니다.

**Comment by ddoddiworld** [comment]
안녕하세요 성호님!

우선 시간 내 주셔서 이슈 달아주셔서 감사합니다!
제가 설명을 두서 없이 말해서 다 끝나고 뒤늦게 '아! 이걸 이렇게 설명했어야 했는데...!' 하는게 조금 있어서 아쉬웠는데
이렇게 좋은 피드백만 한가득 작성해 주셔서 감사합니다😁

Select 부분의 key를 생각해보니 제가 넘어가버렸네요😟!! 생각지도 못했는데 감사합니다.
앞으로는 다 만들고 나서 개발자도구로 발생하는 오류도 함께 확인하는 습관을 들여야겠네요.

남은 항해도 함께 파이팅합시다!!
