### ISSUE TITLE
Lv 3과제 강권영

### ISSUE THREAD

**Issue by passbreaker1** [ddoddiworld/makeui#4]
버튼 컴포넌트에 프롭으로 색을 전달하면 바뀌고 전달 안 하면 기본값이 있는 방법이 좀 더 능동적으로 좋왔습니다. 
찾아보니 &:last-child 와 같이 맨 마지막에 만 css 적용되는 것과 &:active 는 호버 느낌처럼 쓰신것을 배웠습니다.
가격에서 toString말고 toLocaleString()쓰는 이유는 , 를 구분하기 위한 것을 알게되었습니다.
모달에서는 함수로 해당버튼의 창을 열고 하나의 스테이트로 (null) 열고/닫을 수 있구나 알게 되었습니다.

**Comment by ddoddiworld** [comment]
안녕하세요 권영님!

우선 시간 내 주셔서 이슈 달아주셔서 감사합니다!
권영님과는 페어 리뷰로 처음 대화하게 되었는데 만나서 반가웠습니다.

제가 설명을 두서 없이 말해서 다 끝나고 뒤늦게 '아! 이걸 이렇게 설명했어야 했는데...!' 하는게 조금 있어서 아쉬웠는데
이렇게 좋은 피드백만 한가득 작성해 주셔서 감사합니다😁

개인적으론 css를 좋아해서 이것저것 연구해가면서 작업해 보려고 노력했는데 그 진가를 알아주셔서 감사해요!
권영님의 담당하신 파트가 어렵다고 생각했는데 깔끔하게 잘 구현 하셔서 대단하다고 생각됩니다 👏🏻 👏🏻 👏🏻 

남은 항해도 함께 파이팅합시다!!
